// Multidimensional Arrays - data using the Map Method

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { bookstore } from '@/data/books'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [data, setData] = useState()

  const addingData = () => {
    console.log('adding data')
    setData(bookstore)
    console.log(bookstore)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <button onClick={() => addingData()}>View</button>
      {
        data && data.books.map((b, index) => {
          if (b.category.toLowerCase() == "coding") {
            return (
              <div key={index}>
                  <h3>{b.title}</h3>
                  {
                    b.authors && b.authors.map((a, i) => {
                      return (
                        <div key={index}>
                          {a}
                        </div>
                      )
                    })
                  }
              </div>
            )
          }
        })
      }
      </main>
    </>
  )
}


